schema: '**/*.graphqls'
schemaEntrypoint: 'src/lib/type-defs.graphqls'
documents: '**/*.graphql'
plugins:
  - typescript
  - typescript-operations
  - typescript-react-apollo
cacheDir: src/lib/__generated__
