name: Automated Linting

on:
  pull_request:
    branches: [ $default-branch, feat/* ]

jobs:
  run-linters:
    runs-on: ubuntu-latest

    strategy:
        matrix:
          node-version: [ '14' ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-${{ hashFiles('./yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-nodemodules-

      - name: Install packages
        if: |
          steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install

      - name: Autogenerate GraphQL
        run: yarn codegen

      - name: Run Typescript Checks
        run: yarn lint
